<a href="https://colab.research.google.com/github/hasankachamathvi/LogisticsRegression/blob/main/SVM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score,accuracy_score


In [ ]:
fp= pd.DataFrame(pd.read_csv("/content/iris.csv"))

In [ ]:
fp.head()

Id  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0  1001           5.1          3.5           1.4          0.2  setosa
1  1002           4.9          3.0           1.4          0.2  setosa
2  1003           4.7          3.2           1.3          0.2  setosa
3  1004           4.6          3.1           1.5          0.2  setosa
4  1005           5.0          3.6           1.4          0.2  setosa

In [ ]:
fp.tail()

Id  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
145  1146           6.7          3.0           5.2          2.3  virginica
146  1147           6.3          2.5           5.0          1.9  virginica
147  1148           6.5          3.0           5.2          2.0  virginica
148  1149           6.2          3.4           5.4          2.3  virginica
149  1150           5.9          3.0           5.1          1.8  virginica

In [ ]:
x= fp.iloc[:,:4]
y= fp.iloc[:,4]

In [ ]:
x.shape

(150, 4)

In [ ]:
y.value_counts()

Petal.Width
0.2    29
1.3    13
1.5    12
1.8    12
1.4     8
2.3     8
0.4     7
1.0     7
0.3     7
2.1     6
2.0     6
1.2     5
0.1     5
1.9     5
1.6     4
2.5     3
2.2     3
1.1     3
2.4     3
1.7     2
0.6     1
0.5     1
Name: count, dtype: int64

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.8, test_size=0.2, random_state=100)

In [ ]:
fp.drop(['Id',], axis=1,inplace=True)

In [ ]:
fp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Sepal.Length  150 non-null    float64
 1   Sepal.Width   150 non-null    float64
 2   Petal.Length  150 non-null    float64
 3   Petal.Width   150 non-null    float64
 4   Species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [ ]:
fp.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
from sklearn.svm import SVC

In [ ]:
model=SVC()#we are using default values

In [ ]:
# Re-define x and y using the modified 'data' DataFrame (Id column already dropped)
x = fp.drop('Species', axis=1) # Features: Sepal.Length, Sepal.Width, Petal.Length, Petal.Width
y = fp['Species'] # Target: Species

# Re-split the data with the corrected x and y
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.8, test_size=0.2, random_state=100)

# Now fit the model with the correct y_train (categorical Species)
model.fit(x_train, y_train)

SVC()

In [ ]:
x

Id  Sepal.Length  Sepal.Width  Petal.Length
0    1001           5.1          3.5           1.4
1    1002           4.9          3.0           1.4
2    1003           4.7          3.2           1.3
3    1004           4.6          3.1           1.5
4    1005           5.0          3.6           1.4
..    ...           ...          ...           ...
145  1146           6.7          3.0           5.2
146  1147           6.3          2.5           5.0
147  1148           6.5          3.0           5.2
148  1149           6.2          3.4           5.4
149  1150           5.9          3.0           5.1

[150 rows x 4 columns]

In [ ]:
model.kernel#find the defualt kernal

'rbf'

In [ ]:
print(model.get_params())#obtain the parameter of the model

{'C': 1.0, 'break_ties': False, 'cache_size': 200, 'class_weight': None, 'coef0': 0.0, 'decision_function_shape': 'ovr', 'degree': 3, 'gamma': 'scale', 'kernel': 'rbf', 'max_iter': -1, 'probability': False, 'random_state': None, 'shrinking': True, 'tol': 0.001, 'verbose': False}


In [ ]:
from sklearn.svm import SVC
model= SVC(kernel='poly')
model.fit(x_train,y_train)

SVC(kernel='poly')

In [ ]:
y_pred=model.predict(x_test)

In [ ]:
y_pred

array(['virginica', 'setosa', 'virginica', 'setosa', 'virginica',
       'virginica', 'setosa', 'setosa', 'virginica', 'setosa', 'setosa',
       'virginica', 'setosa', 'setosa', 'virginica', 'versicolor',
       'versicolor', 'virginica', 'virginica', 'virginica', 'virginica',
       'setosa', 'virginica', 'setosa', 'versicolor', 'virginica',
       'versicolor', 'setosa', 'versicolor', 'virginica'], dtype=object)

In [ ]:
accuracy=model.score(x_test,y_test)

In [ ]:
accuracy_score(y_test, y_pred)

0.9666666666666667

In [ ]:
y_test

128     virginica
11         setosa
118     virginica
15         setosa
123     virginica
135     virginica
32         setosa
1          setosa
116     virginica
45         setosa
40         setosa
115     virginica
26         setosa
28         setosa
145     virginica
97     versicolor
62     versicolor
77     versicolor
122     virginica
112     virginica
125     virginica
31         setosa
146     virginica
29         setosa
69     versicolor
149     virginica
75     versicolor
20         setosa
73     versicolor
120     virginica
Name: Species, dtype: object

In [ ]:
from sklearn.svm import SVC
model2= SVC(kernel='poly', C=10)#C is the tuning parameter
model2.fit(x_train,y_train)

SVC(C=10, kernel='poly')

In [ ]:
y_pred2=model2.predict(x_test)

In [ ]:
y_pred2

array(['virginica', 'setosa', 'virginica', 'setosa', 'virginica',
       'virginica', 'setosa', 'setosa', 'virginica', 'setosa', 'setosa',
       'virginica', 'setosa', 'setosa', 'virginica', 'versicolor',
       'versicolor', 'versicolor', 'virginica', 'virginica', 'virginica',
       'setosa', 'virginica', 'setosa', 'versicolor', 'virginica',
       'versicolor', 'setosa', 'versicolor', 'virginica'], dtype=object)

In [ ]:
accuracy=model.score(x_test,y_test)

In [ ]:
accuracy_score(y_test, y_pred2)

1.0

In [ ]:
from sklearn.svm import SVC
model3= SVC(kernel='linear', C=10)#C is the tuning parameter
model3.fit(x_train,y_train)

SVC(C=10, kernel='linear')

In [ ]:
#number of classes
num_classes=len(model3.classes_)
print("Number of classes:", num_classes)

print("Number of hyperplanes:", num_classes)

Number of classes: 3
Number of hyperplanes: 3


In [ ]:
model3.coef_

array([[-0.04625854,  0.5211828 , -1.00304462, -0.46412979],
       [-0.00814996,  0.17929913, -0.53789738, -0.29339857],
       [ 1.10233035,  1.10167666, -3.56017852, -4.48968532]])

In [ ]:
model3.intercept_

array([ 1.45284449,  1.51073119, 14.49748498])

you have 4 features, that's why we have 12 coefficition

In [ ]:
model3.n_support_ #no of support vectors

array([3, 6, 6], dtype=int32)

In [ ]:
support_vectors = model3.support_vectors_
print("Support Vectors:")
print(support_vectors)

Support Vectors:
[[4.5 2.3 1.3 0.3]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.4 3.  4.5 1.5]
 [5.9 3.2 4.8 1.8]
 [6.  2.7 5.1 1.6]
 [6.2 2.2 4.5 1.5]
 [6.3 2.5 4.9 1.5]
 [5.1 2.5 3.  1.1]
 [6.  2.2 5.  1.5]
 [6.1 3.  4.9 1.8]
 [6.3 2.8 5.1 1.5]
 [6.2 2.8 4.8 1.8]
 [4.9 2.5 4.5 1.7]
 [6.  3.  4.8 1.8]]
